name: Avoimien menetelmien lunttisivusto
description: Something here
markdown: redcarpet
redcarpet:
   extensions: ["tables"]
pygments: false
baseurl: "http://muuankarski.kapsi.fi/luntti/"
url: "http://muuankarski.kapsi.fi/luntti/"
