name: Avoimien menetelmien lunttisivusto
description: Something here
markdown: kramdown
redcarpet:
   extensions: ["tables"]
pygments: false
baseurl: "http://muuankarski.github.io/luntti/"
url: "http://muuankarski.github.io/luntti/"
