---
layout: default
title: "Manipulointi"
author: "Markus Kainu"
date: "24.08.2014"
---

```{r, echo=FALSE}
library(knitr)
opts_chunk$set(list(echo=TRUE,eval=FALSE,cache=FALSE,warning=FALSE,message=FALSE,fig.dir= "figure/"))
```


# Datan manipuloimista


## Datan kääntäminen

```{r}
# pitkästä leveään
library(reshape2)
df.wide <- dcast(df.long, region + cntry ~ year, value.var="value")
# leveästä to pitkään
library(reshape2)
df.long <- melt(df.wide, id.vars=c("region","cntry"))
```

## Na solujen poistaminen

```{r}
# yksi muuttuja
df <- df[!is.na(df$Var1),]
# kaikki rivit joilla na
df2 <- na.omit(df) 
```

## Faktorit numeerisiksi

```{r}
df$f <- factor(df$f)
df$f.num <- as.numeric(levels(df$f))[df$f]
```

## Removing duplicats


```{r}
df <- df[!duplicated(dat[c("var1","var2","var3")]),]
```


## Renaming variables

```{r}
# built-in
names(df)[names(df)=="oldName"] <- "newName"
# using plyr
rename(df, c("oldName1"="newName2", "oldName2"="newName2"))
```

## Subset data

```{r}
# based on regexpr in string
df <- df[ with(df, grepl("phrase", var1), ]


```

## Remove all objects but

```{r}
rm(list=setdiff(ls(), "x"))
```

## Järjestä data

```{r}
df <- mtcars
df$merkki <- row.names(df)
head(df)
# 
df <- df[order(df$qsec),]
# tai with ja useampi muuttuja
df <- df[with(df, order(qsec, -hp)), ]
head(df)
# fatorilevelit jatkuvan muuttujan mukaan (order) 
## järjestämisdata voi myös olla toinen data (esim. maa-data lapsiköyhyyden mukaan, jolloin voi sortata dodge/stacked tolppakuvioita))
df$merkki <- factor(df$merkki, levels=df[order(df$hp),]$merkki)
#
df$merkki <- factor(df$merkki, levels=df_subset[order(df_subset$hp),]$merkki)
```

**Tulosta pilkulla erotettu vektori**

```{r}
vector <- c("one","two","three")
cat(paste(shQuote(vector, type="cmd"), collapse=", "))

vector <- c(1,2,3)
cat(paste(vector, collapse=","))

```


[source](http://stackoverflow.com/questions/6190051/how-can-i-remove-all-objects-but-one-from-the-workspace-in-r)


## Satunnaisia linkkejä

- [tidy data and tidy tools](http://vita.had.co.nz/papers/tidy-data-pres.pdf)
- [Lists and data cleaning](https://dl.dropbox.com/u/7710864/courseraPublic/otherResources/lecture3/index.html#1)
- [Hadley Wickham on regular expressions](http://stat405.had.co.nz/lectures/14-reg-exp.pdf)


